apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
spec:
  releaseName: kyverno
  chart:
    spec:
      chart: kyverno
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kyverno
      version: 3.2.5
  dependsOn:
  - name: prometheus
    namespace: prometheus
  interval: 1h0m0s
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  # https://github.com/kyverno/kyverno/blob/kyverno-policies-chart-3.2.4/charts/kyverno/values.yaml
  values:
    crds:
      migration:
        podAnnotations:
          linkerd.io/inject: disabled

    grafana:
      enabled: true

    features:
      logging:
        format: json

    admissionController:
      serviceMonitor:
        enabled: true

    backgroundController:
      serviceMonitor:
        enabled: true
      rbac:
        clusterRole:
          extraResources:
          - apiGroups:
            - ""
            resources:
            - namespaces
            verbs:
            - get
            - list
            - patch
            - update
          - apiGroups:
            - batch
            resources:
            - cronjobs
            - jobs
            verbs:
            - get
            - list
            - patch
            - update

    cleanupController:
      serviceMonitor:
        enabled: true

    reportsController:
      serviceMonitor:
        enabled: true

    webhooksCleanup:
      podAnnotations:
        linkerd.io/inject: disabled

    cleanupJobs:
      admissionReports:
        podAnnotations:
          linkerd.io/inject: disabled
      clusterAdmissionReports:
        podAnnotations:
          linkerd.io/inject: disabled
      updateRequests:
        podAnnotations:
          linkerd.io/inject: disabled
      ephemeralReports:
        podAnnotations:
          linkerd.io/inject: disabled
      clusterEphemeralReports:
        podAnnotations:
          linkerd.io/inject: disabled

    policyReportsCleanup:
      podAnnotations:
        linkerd.io/inject: disabled
