# This patch is required in order to disable Linkerd sidecar injection (via annotation) 
# Src: https://github.com/rancher/local-path-provisioner/blob/v0.0.24/deploy/local-path-storage.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-path-config
data:
  config.json: |-
    {
      "nodePathMap":[{
        "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
        "paths":["/var/local-path-provisioner"]
      }]
    }
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
      annotations:
        linkerd.io/inject: disabled
    spec:
      containers:
      - name: helper-pod
        image: docker.io/kindest/local-path-helper:v20230510-486859a6
        imagePullPolicy: IfNotPresent
  setup: |-
    #!/bin/sh
    set -eu
    mkdir -m 0777 -p "$VOL_DIR"
  teardown: |-
    #!/bin/sh
    set -eu
    rm -rf "$VOL_DIR"
