apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-operator
spec:
  releaseName: opentelemetry-operator
  chart:
    spec:
      chart: opentelemetry-operator
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: opentelemetry-operator-system
      version: 0.63.0
  dependsOn:
  - name: prometheus
    namespace: prometheus
  install:
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  interval: 1h0m0s
  # https://github.com/open-telemetry/opentelemetry-helm-charts/blob/opentelemetry-operator-0.63.0/charts/opentelemetry-operator/values.yaml
  values:
    manager:
      collectorImage:
        repository: otel/opentelemetry-collector-contrib
        tag: 0.103.1
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
        defaultRules:
          enabled: true
      createRbacPermissions: true
    priorityClassName: system-cluster-critical
    topologySpreadConstraints:
    - maxSkew: 2
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: opentelemetry-operator
          app.kubernetes.io/component: controller-manager
