apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opentelemetry-operator-system

resources:
- helmrepository.yaml
- helmrelease.yaml
- namespace.yaml

configMapGenerator:
- name: opentelemetry-dashboards
  files:
  - dashboards/opentelemetry-collector-data-flow.json
  - dashboards/opentelemetry-collector.json
  options:
    labels:
      grafana_dashboard: "1"
