apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus

configurations:
- kustomizeconfig.yaml

resources:
- helmrepository.yaml
- helmrelease.yaml
- namespace.yaml

patches:
- path: helmrelease-kube-state-metrics-patch.yaml

#secretGenerator:
#- name: thanos-objstore-config
#  files:
#  - config/thanos-storage-config.yaml
